### ISSUE TITLE
enum bitmasks in template

### ISSUE THREAD

**Issue by BeErikk** [Dalzhim/ArticleEnumClass-v2#1]
I really like the elegant simplicity achieved by your enum classes!

However, I got stuck on a problem using them in templates. The following code inspired by ATL CWinTraits fails. Any idea of a solution?

```
enum class ServiceHandler : uint16_t 
{
    accept_none                     = 0u,
    accept_stop                     = SERVICE_ACCEPT_STOP,
    accept_pausecontinue            = SERVICE_ACCEPT_PAUSE_CONTINUE,
    accept_shutdown                 = SERVICE_ACCEPT_SHUTDOWN,
    accept_paramchange              = SERVICE_ACCEPT_PARAMCHANGE,
    accept_netbindchange            = SERVICE_ACCEPT_NETBINDCHANGE,
    accept_hardwareprofilechange    = SERVICE_ACCEPT_HARDWAREPROFILECHANGE,
    accept_powerevent               = SERVICE_ACCEPT_POWEREVENT,
    accept_sessionchange            = SERVICE_ACCEPT_SESSIONCHANGE,
    accept_preshutdown              = SERVICE_ACCEPT_PRESHUTDOWN,
    accept_timechange               = SERVICE_ACCEPT_TIMECHANGE,
    accept_triggerevent             = SERVICE_ACCEPT_TRIGGEREVENT,
    accept_userlogoff               = SERVICE_ACCEPT_USER_LOGOFF,
    accept_lowresources             = SERVICE_ACCEPT_LOWRESOURCES,
    accept_systemlowresources       = SERVICE_ACCEPT_SYSTEMLOWRESOURCES
};
enableEnumClassBitmask(ServiceHandler);

template <ServiceHandler Taccepttraits = ServiceHandler::accept_none>
class ServiceAcceptTraits
{
public:
    ServiceHandler GetAcceptTraits(void) const noexcept  { return Taccepttraits; }
};
using StandardAcceptTraits = ServiceAcceptTraits<
      ServiceHandler::accept_stop
    | ServiceHandler::accept_pausecontinue
    | ServiceHandler::accept_shutdown>;
```
This is intended to be used like so:
```
template <
	class TderivedClass, 
	const wchar_t* Tservicename, 
	class TServiceAcceptTraits = StandardAcceptTraits>
class NO_VTABLE ServiceBase
{
};
```
compilation gives

`error C2440: 'specialization': cannot convert from 'bitmask<ServiceHandler>' to 'ServiceHandler'`

**Comment by Dalzhim** [comment]
If you refer to the table in the Readme, you'll see that the result of `operator|` is a `bitmask<T>`. You can also refer to [my blog post](https://dalzhim.github.io/2017/08/11/Improving-the-enum-class-bitmask/) for a more thorough explanation. Based on the example you gave, I believe your template should be: `template class TderivedClass, const wchar_t* Tservicename, class TServiceAcceptTraits = bitmask<StandardAcceptTraits>> class NO_VTABLE ServiceBase {};`

**Comment by BeErikk** [comment]
Thanks for the kind attention and the suggestion. This is a bit over my head.

The problem is that ServiceAcceptTraits works like a kind of property, just as ATL::CWinTraits holds the style of a Win32 Window, a DWORD made out of a combination of specific styles. In my case, ultimately there is a uint16_t member assigned by the ServiceAcceptTraits from a combination of specific functionality values. The fact that only a combination of specific values is valid makes it tempting to use an enum class. Sadly I can't get it to work. So currently, I commented out the _class_ specification in my enums and reverted to this based on normal enums:

```
template <uint16_t Taccepttraits = ServiceHandler::accept_none>
class ServiceAcceptTraits
{
public:
    uint16_t GetAcceptTraits(void) const noexcept  { return Taccepttraits; }
};
using StandardAcceptTraits = ServiceAcceptTraits<
      ServiceHandler::accept_stop
    | ServiceHandler::accept_pausecontinue
    | ServiceHandler::accept_shutdown>;

```
The enumclass bool operator is useful for validity tests, but I think I need a kind of enum valuetype operator. I think using casts or special types takes away the elegance of the solution which probably makes it better to revert to normal enums.

**Comment by Dalzhim** [comment]
I believe I missed the real issue in my previous reply with the line `using StandardAcceptTraits = ServiceAcceptTraits<ServiceHandler::accept_stop | ServiceHandler::accept_pausecontinue | ServiceHandler::accept_shutdown>;`.
You are trying to encode the mask into the type system and the result of `operator|` doesn't do that for you right now. You could probably get the desired result with the following code:
```
using StandardAcceptTraits = ServiceAcceptTraits<
      (ServiceHandler::accept_stop
    | ServiceHandler::accept_pausecontinue
    | ServiceHandler::accept_shutdown).value>;
```


**********
#### Original reply I was about to write, but might still be enlightening…
There is a semantic difference between a mask and an enumerator and reflecting that semantic difference in the type system makes it possible to prevent additional programming mistakes. When handling the `bitmask<T>` type, you can access the underlying value (an integral type) using its `value` member.

If you'd rather not have the bitmask type, you can give a try to the previous enum class helpers used in the [first blog post](https://dalzhim.github.io/2016/02/16/enum-class-bitfields/) I made on the subject.

**Comment by BeErikk** [comment]
Yes, thanks!! The following works

```
template <uint16_t Taccepttraits = 0>
class ServiceAcceptTraits
{
public:
    uint16_t GetAcceptTraits(void) const noexcept  { return Taccepttraits; }
    void SetAcceptTraits(uint16_t trait) const noexcept  { Taccepttraits = trait; }
};
using StandardAcceptTraits = ServiceAcceptTraits<
     (ServiceHandler::accept_stop
    | ServiceHandler::accept_pausecontinue
    | ServiceHandler::accept_shutdown).value>;

```
or with other words
```
bitmask<enum ServiceHandler> mask2 = ServiceHandler::accept_stop | ServiceHandler::accept_shutdown;
uint16_t mask3 = mask2.value;
uint16_t mask4 = (ServiceHandler::accept_stop | ServiceHandler::accept_shutdown).value;

```
Hiding bitmask and having an `operator underlying_type()` (?) would be nice though

**Comment by Dalzhim** [comment]
Hiding `bitmask<T>` is not an option as it is what makes it possible to detect more bitmask-related programming errors at compile-time. Same goes for `operator underlying_type()` as this would reintroduce bug-prone implicit conversions that were eliminated by using `enum class` rather than `enum`.

**Comment by BeErikk** [comment]
OK, it was just a suggestion. I suspected `operator underlying_type()` would be regarded as somewhat take away the point of _enum class_, but if restricted to the bitmask class I would like it very much. Isn't the values validated already in the bitmask? Anyway, I tried the following simple patch
[enumclass.diff.txt](https://github.com/Dalzhim/ArticleEnumClass-v2/files/3335806/enumclass.diff.txt)
or at line 63
```
    constexpr operator underlying_type(void) const
    {
        return value;
    }
```
which makes the following convinency work (just as normal enums)
`uint16_t mask5 = ServiceHandler::accept_stop | ServiceHandler::accept_shutdown;`
The main.cpp test works as well

**Comment by Dalzhim** [comment]
You're welcome to use that patch if it helps you. The reason I don't want to include it is that I want the following piece of code to raise a compilation error.

```
void f(int);

f(ServiceHandler::accept_stop | ServiceHandler::accept_shutdown);
```

**Comment by BeErikk** [comment]
I agree, the following which is allowed by the patch is even worse 
`auto mask1 = ServiceHandler::accept_stop | ServiceHandler::accept_shutdown | 10;`

None of the enum class bitmask solutions I've seen is dealing with the issue of getting the resulting value in a bitmask, other than your _.value_ hack above that is. I guess the conclusion is to either use the hack or use normal enums.
