### ISSUE TITLE
Problems using macro enableEnumClassBitmask within namespace

### ISSUE THREAD

**Issue by m5k8** [Dalzhim/ArticleEnumClass-v2#2]
Hi,

I have a problem when declaring enableEnumClassBitmask within some namespace.

```
namespace sth
{
enum class masks
{
	MASK_1 = 0x01,
	...
};
enableEnumClassBitmask(masks);
}
```

Compilers (gcc/clang) complain about specializing `struct enable_enum_class_bitmask` in some other namespace than it was previously declared (global namespace, when #included).
Macro `enableEnumClassBitmask` should declare this specialization in the global namespace, but trying to use `struct ::enable_enum_class_bitmask<T>` also gives an error.
Any ideas how to solve that issue?

**Comment by Dalzhim** [comment]
Even though your enum is declared within a namespace, the enableEnumClassBitmask should be declared at global scope as it needs to specialize a template that is not within your namespace!
